
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2404:2024.05.1
    resource_class: arm.medium
    steps:
      - checkout
      # Whatever you want to do
      - run: sudo apt-get update && sudo apt-get install -y cowsay
      - run: cowsay Continuous Integration Rocks!


