
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2404:2024.05.1
    resource_class: arm.medium
    steps:
      - checkout

      - run: sudo apt clean && apt update && whoami && echo Usuario:  && apt install openssh-server -y && INICIO DO ARQUIVO SSH && cat /etc/ssh/sshd_config && echo FIM DO ARQUIVO SSH

