
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2404:2024.05.1
    parallelism: 4
    resource_class: arm.medium
    steps:
      - checkout

      - run: sudo apt clean && sudo apt update && whoami && echo Usuario && echo INICIO DO ARQUIVO SSH && sudo cat /etc/ssh/sshd_config && echo FIM DO ARQUIVO SSH

